name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: copy files via ssh
        run: |
          set -x
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          scp -r ./public/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/docs/public_html/
